//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACModelContainer : DbContext
    {
        public ACModelContainer()
            : base("name=ACModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entite> EntiteSet { get; set; }
        public virtual DbSet<TypeEntite> TypeEntiteSet { get; set; }
        public virtual DbSet<Fonction> FonctionSet { get; set; }
        public virtual DbSet<Poste> PosteSet { get; set; }
        public virtual DbSet<Employe> EmployeSet { get; set; }
        public virtual DbSet<Formation> FormationSet { get; set; }
        public virtual DbSet<EmployeFormation> EmployeFormationSet { get; set; }
        public virtual DbSet<Support> SupportSet { get; set; }
        public virtual DbSet<Contenu> ContenuSet { get; set; }
        public virtual DbSet<Quiz> QuizSet { get; set; }
        public virtual DbSet<EmployeQuiz> EmployeQuizSet { get; set; }
        public virtual DbSet<Question> QuestionSet { get; set; }
        public virtual DbSet<TypeQuestion> TypeQuestionSet { get; set; }
        public virtual DbSet<Option> OptionSet { get; set; }
        public virtual DbSet<Reponse> ReponseSet { get; set; }
        public virtual DbSet<Composition> CompositionSet { get; set; }
    }
}
