//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeFormation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeFormation()
        {
            this.EmployeQuiz = new HashSet<EmployeQuiz>();
        }
    
        public int Id { get; set; }
        public System.DateTime At { get; set; }
        public System.DateTime Active { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
    
        public virtual Poste Poste { get; set; }
        public virtual Formation Formation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeQuiz> EmployeQuiz { get; set; }
    }
}
