//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeQuiz
    {
        public int Id { get; set; }
        public System.DateTime At { get; set; }
        public System.DateTime DateFin { get; set; }
        public bool Active { get; set; }
    
        public virtual EmployeFormation EmployeFormation { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual Composition Composition { get; set; }
    }
}
