//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fonction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fonction()
        {
            this.Postes = new HashSet<Poste>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Nom { get; set; }
        public System.DateTime At { get; set; }
        public bool EstTransversale { get; set; }
        public bool EstTop { get; set; }
    
        public virtual TypeEntite TypeEntite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poste> Postes { get; set; }
    }
}
