//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poste()
        {
            this.EmployeFormation = new HashSet<EmployeFormation>();
        }
    
        public int Id { get; set; }
        public System.DateTime At { get; set; }
        public bool Active { get; set; }
    
        public virtual Entite Entite { get; set; }
        public virtual Fonction Fonction { get; set; }
        public virtual Employe Employe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeFormation> EmployeFormation { get; set; }
    }
}
