//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentCenterDBEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponse
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public string Proposition { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Option Option { get; set; }
        public virtual Composition Composition { get; set; }
    }
}
